<?php
/**
 * Created by PhpStorm.
 * User: too
 * Date: 2018/7/20
 * Time: 16:01
 * @author too <hayto@foxmail.com>
 */

namespace Thsoft\base;


class Component extends BaseObject
{
    protected $_components = [];
    protected $_definitions = [];
    
    public function setComponents(array $components): void
    {
        parent::setComponents($components); // TODO: Change the autogenerated stub
    }
}